DELETE http://localhost:3000/api/persons/659c56d9936db683efd14732

###

GET http://localhost:3000/info

###

GET http://localhost:3000/api/persons/659c56d9936db683efd14732

###

GET http://localhost:3000/api/persons

###

POST http://localhost:3000/api/persons
Content-Type: application/json

{
    "name": "Kamau",
    "number": "040-1234500"
}
